# costmap.yaml
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.5
  rolling_window: false
  always_send_full_costmap: true
  plugins:
    - {name: static_layer, type: "nav2_costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

  static_layer:
    enabled: true
    map_topic: map
    subscribe_to_updates: true
    track_unknown_space: true
    use_maximum: false

  obstacle_layer:
    enabled: true
    max_obstacle_height: 2.0
    combination_method: 1
    obstacle_range: 3.0
    raytrace_range: 3.5
    observation_sources: scan
    scan:
      topic: /scan
      sensor_frame: lidar_link
      data_type: LaserScan
      marking: true
      clearing: true
      min_obstacle_height: 0.25
      max_obstacle_height: 2.0

  inflation_layer:
    enabled: true
    cost_scaling_factor: 5.0
    inflation_radius: 0.5
    inflation_radius: 0.35

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  plugins:
    - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

  obstacle_layer:
    enabled: true
    max_obstacle_height: 2.0
    combination_method: 1
    obstacle_range: 2.5
    raytrace_range: 3.0
    observation_sources: scan
    scan:
      topic: /scan
      sensor_frame: lidar_link
      data_type: LaserScan
      marking: true
      clearing: true
      min_obstacle_height: 0.25
      max_obstacle_height: 2.0

  inflation_layer:
    enabled: true
    cost_scaling_factor: 10.0
    inflation_radius: 0.35

# Robot footprint configuration (adjust based on your URDF)
footprint: [[-0.15, -0.15], [-0.15, 0.15], [0.15, 0.15], [0.15, -0.15]]
# Alternative circular footprint:
# robot_radius: 0.2

# Common parameters
use_sim_time: true