# nav2_params.yaml
amcl:
  ros__parameters:
    initial_pose: {x: 0.0, y: 0.0, z: 0.0}
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    progress_checker:
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

planner_server:
  ros__parameters:
    use_sim_time: true

behavior_server:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true

collision_monitor:
  ros__parameters:
    enabled: True
    min_obstacle_height: 0.25
    max_obstacle_height: 2.0

costmap_2d: 
  ros__parameters: 
    @merge: $(find-pkg-share diff_drive_robot)/config/costmap.yaml